import Head from "next/head";
import { useState } from "react";
import { Button } from "flowbite-react";
import Balance from "@/components/Balance";
import { useCashu } from "@/hooks/useCashu";
import { useNwc } from "@/hooks/useNwc";
import { addProofsToBalance } from "@/utils/crud";

export default function Home() {
  const [mintAmount, setMintAmount] = useState("");
  const [receiverPubkey, setReceiverPubkey] = useState("");
  const [sendAmount, setSendAmount] = useState("");

  const relay = "wss://nos.lol";

  const mintUrl = process.env.NEXT_PUBLIC_MINT_URL;

  const { getEcashViaLn, getProofsToSend } = useCashu({ mintUrl });
  const { cashuKeysend, pubkey } = useNwc({ listenRelay: relay });

  const handleNwcSend = async () => {
    if (!receiverPubkey || !sendAmount) {
      console.error("Receiver pubkey and send amount are required");
      return;
    }

    const proofsToSend = await getProofsToSend(Number(sendAmount));

    try {
      await cashuKeysend(proofsToSend, receiverPubkey);
    } catch (e) {
      console.error("Error sending via NWC", e);
      addProofsToBalance(proofsToSend);
    }
  };

  return (
    <>
      <Head>
        <title>Nutty NWC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen justify-center items-center">
        <div className="mb-8">
          <div>
            <p>Pubkey: {pubkey}</p>
            <p>Relay: {relay}</p>
          </div>
        </div>

        <Balance />

        <div className="mb-8 p-8 border border-green-600">
          <div className="flex flex-row mb-4">
            <Button
              onClick={() => getEcashViaLn(Number(mintAmount))}
              color="success"
            >
              Get Ecash via LN
            </Button>

            <input
              className="ml-4 p-2 text-gray-700"
              placeholder="Num sats to get"
              type="number"
              value={mintAmount}
              onChange={(e) => setMintAmount(e.target.value)}
            />
          </div>

          <p>
            <strong>
              NOTE: only works if you have webln enabled in your browser <br />
              (ie. Alby browser extension)
            </strong>
          </p>
        </div>

        <div className="flex flex-col p-8 border-blue-700 border">
          <div className="flex flex-row mb-4">
            <div className="flex flex-col items-center">
              <input
                className="ml-4 p-2 text-gray-700"
                placeholder="Enter receiver pubkey"
                type="text"
                value={receiverPubkey}
                onChange={(e) => setReceiverPubkey(e.target.value)}
              />
              <p>Receiver pubkey</p>
            </div>

            <div className="flex flex-col items-center">
              <input
                className="ml-4 p-2 text-gray-700"
                placeholder="Enter amount"
                type="number"
                value={sendAmount}
                onChange={(e) => setSendAmount(e.target.value)}
              />
              <p>Amount Sat</p>
            </div>
          </div>
          <Button onClick={handleNwcSend}>Send Ecash via NWC</Button>
        </div>
      </main>
    </>
  );
}
